name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: CI skip
      uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true
    - name: cache downloads
      uses: actions/cache@v1
      with:
        path: ~/.cache/cerbero-sources/
        key: cerbero-sources
    - name: cache build-tools
      uses: actions/cache@v1
      if: false
      with:
        path: cerbero-artifacts/cerbero/build/
        key: build-tools
    - name: apt update
      run: |
        sudo apt-get update
    - name: apt install
      run: |
        echo y | sudo apt-get install autogen faust libeigen3-dev
    - name: stupid NDK setup workaround for GitHub Actions
      run: sudo mkdir -p /usr/local/lib/android/sdk/ndk && sudo chmod 777 /usr/local/lib/android/sdk/ndk
    - name: prepare
      run: make prepare
    - name: build lv2
      run: make package-aap
    - name: upload aap artifact zip
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: android-lv2-binaries.zip
        path: android-lv2-binaries.zip
    - name: upload aap artifact prefab
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: aap-lv2-natives.aar
        path: prefab/aap-lv2-natives/aap-lv2-natives.aar
    - name: build libsndfile
      run: make package-libsndfile
    - name: upload libsndfile artifact zip
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: android-libsndfile-binaries.zip
        path: android-libsndfile-binaries.zip
    - name: build guitarix
      run: make package-guitarix
    - name: upload guitarix artifact zip
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: aap-guitarix-binaries.zip
        path: aap-guitarix-binaries.zip
    - name: build dragonfly-reverb
      run: make package-dragonfly-reverb
    - name: upload dragonfly-reverb artifact zip
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: android-dragonfly-reverb-binaries.zip
        path: android-dragonfly-reverb-binaries.zip

