name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: apt install
      run: |
        echo y | sudo apt-get install autogen faust
    - name: prepare
      run: make prepare
    - name: cache downloads
      uses: actions/cache@v1
      with:
        path: ~/.cache/cerbero-sources/
        key: cerbero-sources
    - name: cache build-tools
      uses: actions/cache@v1
      with:
        path: cerbero-artifacts/cerbero/build/
        key: build-tools
    - name: build
      run: make package
    - name: upload artifact zip
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: zip
        path: android-lv2-binaries.zip
    - name: upload artifact prefab
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: aar
        path: prefab/aap-lv2-natives/aap-lv2-natives.aar


